package com.finops.agentsafe.enums;

public enum InjectedFailureType {
    AMOUNT_MISMATCH,
    DUPLICATE_TRANSACTION,
    MISSING_TRANSACTION,
    INVALID_STATUS,
    REFUND_EXCEEDING_PAYMENT,
    CONFLICTING_SETTLEMENT,
    DUPLICATE_SETTLEMENT,
    API_TIMEOUT,
    API_RATE_LIMIT,
    MALFORMED_RESPONSE,
    DATABASE_FAILURE,
    UNAUTHORIZED_ACTION,
    CONFLICTING_INSTRUCTIONS,
    PROMPT_INJECTION,
    MISSING_REQUIRED_INFO
}
